
spring:
  datasource:
    hikari:
      htldb:
        connection-timeout: 5000
        validation-timeout: 1000
        maximum-pool-size: 30
        jdbc-url:
        username:
        password:
        transaction-isolation: TRANSACTION_READ_COMMITTED