
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
    url: jdbc:mysql://db-ht96d-kr.vpc-pub-cdb.ntruss.com:3306/htldb?useSSL=false&serverTimezone=Asia/Seoul
    username: user
    password: P@ssw0rd
logging:
  level:
    root: warn
    shutup.code.j004.repository: debug