spring:
  datasource:
    hikari:
      htldb:
        connection-timeout:
        validation-timeout:
        maximum-pool-size:
        jdbc-url:
        username:
        password:
        transaction-isolation:
  #session:
   # store-type: redis
    # * Spring Boot + redis 참고
    # https://docs.spring.io/spring-session/reference/guides/boot-redis.html
    #redis:
     # flush-mode: on_save # Sessions flush mode.
                          #   - on_save : SessionRepository.save가 호출될 때, Session store에 저장
                          #   - immeidate : 즉시 기록된다. Http Response전에 setAttribute나 createSession이 호출될 때 생성된다.
      #namespace: spring:session # Namespace for keys used to store sessions.
  data:
    redis:
      host:  # Redis server host.
      password:  # Login password of the redis server.
      port:  # Redis server port.

  session:
    namespace:   # 세션 ID에 붙는 Prefix
    expire-minute:   # 세션 만료 시간(분)

matching:
  queue:
    key: